animo/siera-cli

agent/src/error.rs, cli/src/cli.rs, cli/src/help_strings.rs, cli/src/modules/configuration.rs, cli/src/register.rs, cli/src/utils/config.rs, cloudagent-python/src/agent_python/agent.rs, cloudagent-python/src/cloud_agent.rs, cloudagent-python/src/web.rs
- Adds an auth token for a multi tenancy agent via config or as an option in the cli
=> feat: token

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Create new issue templates

cli/src/help_strings.rs, cli/src/modules/proof.rs
=> fix: added help strings for present proof

cli/src/error.rs, cli/src/utils/config.rs
=> fix: read home from localhost

cli/src/utils/mod.rs, cloudagent-python/src/agent_python/proof.rs
@TimoGlastra noticed a bug when requesting a proof. This fixes this issue.
=> fix: added version to proof request

docs/features/environments.md
Signed-off-by: morrieinmaas <moritz@animo.id>
closes #152
=> geat: add Windows powershell instructions for config write

agent/Cargo.toml, automations/Cargo.toml, cli/Cargo.toml, cloudagent-python/Cargo.toml
=> build: updated version

pkg/.SRCINFO, pkg/PKGBUILD
Signed-off-by: morrieinmaas <moritz@animo.id>
=> change the pkg files to be agent not aries

Makefile, crates/cli/src/modules/multitenancy.rs, tests/helpers.rs
* also made the e2e tests run 4 at a time (see Makefile) changes
* made the create wallet log entire response from agent so that we can use the token in the e2e tests
=> chore: e2e tests using agent cli for multitenancy

.github/workflows/e2e-tests.yml
=> GitHub workflow for e2e tests

.github/workflows/build-and-release.yml
wip - let's see whether that works
=> feat: add debian artifact in github actions

.github/workflows/aur-release.yml, .github/workflows/brew-release.yml, .github/workflows/build-and-release.yml
=> build: fix the package and removed the triggers

.github/workflows/choco-release.yml
=> fix: removed useless trigger

.github/workflows/e2e-tests.yml, Cargo.toml
=> build(e2e-test): remove lock flag

.github/workflows/brew-release.yml
=> build: follow link to get correct data

.github/workflows/build-and-release.yml
=> fix: deb upload and rename windows folder 

.github/workflows/brew-release.yml
by pointing to the correct repo
=> fix: brew release pipeline

.github/workflows/aur-release.yml, .github/workflows/brew-release.yml, .github/workflows/choco-release.yml
=> feat: trigger release pipes from commit message

.github/workflows/aur-release.yml, .github/workflows/brew-release.yml, .github/workflows/choco-release.yml
Attempt to have the release triggers as desired.
=> build: commit message release triggers

Cargo.lock, crates/automations/src/automations/create_credential_definition.rs, crates/automations/src/automations/credential_offer.rs, crates/cli/src/modules/automation.rs, tests/README.md
=> fix(automate): reuse credential definition logic

crates/agent/src/modules/mod.rs, crates/agent/src/modules/webhook.rs, crates/cli/src/cli.rs, crates/cli/src/help_strings.rs, crates/cli/src/modules/mod.rs, crates/cli/src/modules/webhook.rs, crates/cli/src/register.rs, crates/cloudagent-python/src/cloudagent/mod.rs, crates/cloudagent-python/src/cloudagent/webhook.rs
=> fix(webhook): singular

README.md
=> docs: updated roadmap to reflect new changes

.github/workflows/build-and-release.yml, .github/workflows/crates-release.yml
=> build: fix release pipeline

.github/workflows/build-and-release.yml, .github/workflows/crates-release.yml
=> build: fix debian and crates release

.github/workflows/build-and-release.yml
=> build: disable debian build

.github/workflows/build-and-release.yml
=> chore: fix release pipeline

.github/workflows/build-and-release.yml
also remove the mv deb package from release
=> build: fix artifacts release pipeline

pkg/choco/siera.nuspec
=> chore: update nuspec to pacify choclatey moderation

.github/workflows/check.yml, .github/workflows/metrics.yml, Cargo.lock, crates/afj-rest/Cargo.toml, crates/agent/Cargo.toml, crates/automations/Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/modules/connection.rs, crates/cli/src/modules/oob.rs, crates/logger/Cargo.toml, crates/logger/src/macros.rs
- github metrics
- Updated dependencies
- Make sure we can log lists
=> log metrics

Cargo.toml
Signed-off-by: Berend Sliedrecht <sliedrecht@berend.io>
=> updated version  for new release

Cargo.lock, crates/logger/Cargo.toml
Signed-off-by: Berend Sliedrecht <sliedrecht@berend.io>
=> remove xcb

Cargo.lock, Cargo.toml
Updated the dependencies due to some security issues.
=> update dependencies and use the new resolver
